public extension UITableViewCell {
    static public var autoReuseIdentifier : String {

        return NSStringFromClass(self) + "AutogeneratedIdentifier"
    }
}

public extension UITableView {

    public func dequeue<T: UITableViewCell>(cell cell: T.Type, indexPath: NSIndexPath) -> T? {
        return dequeueReusableCellWithIdentifier(T.autoReuseIdentifier, forIndexPath: indexPath) as? T
    }

    public func registerCell<T: UITableViewCell>(cell : T.Type) {
        registerNib(nibFromClass(cell), forCellReuseIdentifier: cell.autoReuseIdentifier)
    }

    // Private

    private func nibFromClass(type: UITableViewCell.Type) -> UINib? {
        guard let nibName = NSStringFromClass(type).componentsSeparatedByString(".").last else {
            return nil
        }

        return UINib(nibName: nibName, bundle: nil)
    }
}
